# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'Mantle'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'YYKit'

target 'Cooking' do

end

target 'CookingTests' do

end

target 'CookingUITests' do

end

